version: "3.5"
services:
  nats:
    image: nats:latest
    ports:
      - "8222:8222"
      - "4222:4222"
    networks: ["nats"]
  nats-1:
    image: nats:latest
    command: "--cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats:6222"
    networks: ["nats"]
    depends_on: ["nats"]
  nats-2:
    image: nats:latest
    command: "--cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats:6222"
    networks: ["nats"]
    depends_on: ["nats"]

  nats-ui:
    image: sphqxe/nats-webui:latest
    ports:
      - "8080:80"
    networks: ["nats"]
    depends_on: ["nats"]   

networks:
  nats:
    name: nats